// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOh7tZqw8XsR5en2MSryc1-XEDIttM4TM',
    appId: '1:382835040516:web:532093a9f9be4c2a457051',
    messagingSenderId: '382835040516',
    projectId: 'visionaid-cb1a3',
    authDomain: 'visionaid-cb1a3.firebaseapp.com',
    storageBucket: 'visionaid-cb1a3.firebasestorage.app',
    measurementId: 'G-D4YBNCTGLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTlgu3mKc7l4ZDlvSO6R_fgjV2G_x9qV8',
    appId: '1:382835040516:android:e4c8d43b87c38a9a457051',
    messagingSenderId: '382835040516',
    projectId: 'visionaid-cb1a3',
    storageBucket: 'visionaid-cb1a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvOW0StVOOr35pdmuxN0_yRJ7sUmi2yYI',
    appId: '1:382835040516:ios:732ff2fee80009ae457051',
    messagingSenderId: '382835040516',
    projectId: 'visionaid-cb1a3',
    storageBucket: 'visionaid-cb1a3.firebasestorage.app',
    iosBundleId: 'com.visionaid.app.visionAidApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvOW0StVOOr35pdmuxN0_yRJ7sUmi2yYI',
    appId: '1:382835040516:ios:732ff2fee80009ae457051',
    messagingSenderId: '382835040516',
    projectId: 'visionaid-cb1a3',
    storageBucket: 'visionaid-cb1a3.firebasestorage.app',
    iosBundleId: 'com.visionaid.app.visionAidApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOh7tZqw8XsR5en2MSryc1-XEDIttM4TM',
    appId: '1:382835040516:web:7ff0849ab0ff0aa9457051',
    messagingSenderId: '382835040516',
    projectId: 'visionaid-cb1a3',
    authDomain: 'visionaid-cb1a3.firebaseapp.com',
    storageBucket: 'visionaid-cb1a3.firebasestorage.app',
    measurementId: 'G-7RXWNTZY5S',
  );
}
